function beta1 = ...
    Beta1(mass1, mass2, length1, length2, theta1, theta2, omega2, g)

    beta1 = ((-1 * omega2^2 * mass2 * length2 * sin(theta1 - theta2)) / ...
        (mass1 * length1 + mass2 * length1)) - ...
        ((g * sin(theta1)) / (length1));

end