function frame = GenerateFrame(length1, length2, theta1, theta2, ...
    massColor1, massColor2, id)

    figure; axis equal; hold on;
    
    axis([-(length1 + length2 + 0.5), (length1 + length2 + 0.5), ...
        -(length1 + length2 + 0.5), (length1 + length2 + 0.5)]);

    rectangle('Position', [-0.03, -0.03, 0.06, 0.06], 'Curvature', ...
        [1, 1], 'FaceColor', massColor1, 'EdgeColor', massColor1);
    rectangle('Position', [length1 * sin(theta1(id, 2)) - 0.1, ...
        -length1 * cos(theta1(id, 2)) - 0.1, 0.2, 0.2], 'Curvature', ...
        [1, 1], 'FaceColor', massColor1, 'EdgeColor', massColor1);
    rectangle('Position', [length1 * sin(theta1(id, 2)) + ...
        length2 * sin(theta2(id, 2)) - 0.1, -length1 * ...
        cos(theta1(id, 2)) - length2 * cos(theta2(id, 2)) - 0.1, ...
        0.2, 0.2], 'Curvature', [1, 1], 'FaceColor', massColor2, ...
        'EdgeColor', massColor1);
    line([0, length1 * sin(theta1(id, 2))], [0, -length1 * ...
        cos(theta1(id, 2))], 'Color', massColor1, 'LineWidth', 3, ...
        'Marker', 'o', 'MarkerIndices', [1, 2], 'MarkerFaceColor', ...
        massColor1);
    line([length1 * sin(theta1(id, 2)), length1 * sin(theta1(id, 2)) ...
        + length2 * sin(theta2(id, 2))], [-length1 * ...
        cos(theta1(id, 2)), -length1 * cos(theta1(id, 2)) - length2 * ...
        cos(theta2(id, 2))], 'Color', massColor2, 'LineWidth', 3, ...
        'Marker', 'o', 'MarkerIndices', [1, 2], 'MarkerFaceColor', ...
        massColor2);

    frame = getframe(gcf);

end