function [mass1, mass2, length1, length2, g, theta1I, theta2I, ...
    omega1I, omega2I, h, timeFinal, n, massColor1, massColor2] = ...
    GetSystemSpec()

    data = readcell(string(input("System information filename: ", "s")));
    data = data(:, 2);
    [mass1, mass2, length1, length2, g, theta1I, theta2I, ...
        omega1I, omega2I, h, timeFinal, n, massColor1, ...
        massColor2] = data{:};

end